### ISSUE TITLE
Brainstorm hopes and dreams

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/open.sentry.io#3]
In Q1 we intend to launch a new microsite at https://open.sentry.io/ that:

- tells Sentry's story around open source,
- publicly documents our open-source-related processes, and
- helps external folks self-onboard to our open-source community.

The purpose of this ticket is to gather ideas in an open-ended way as to the content of the site.

What content do _you_ want on open.sentry.io?

----

([private](https://app.asana.com/0/1199917466931509/1199917466931514))

**Comment by chadwhitacre** [comment]
> link list for community spaces, explaining which question/topic goes where, also strong hint at paid support

> i want to suggest using comics as a form of media to communicate something
> unsure what

**Comment by chadwhitacre** [comment]
notable / flagship open source projects (`responses`, symbolication libraries)

**Comment by armenzg** [comment]
I would like for a way to show contributions opportunities under our Github org. I've used `good first issues` as a label to help contributors.

**Comment by chadwhitacre** [comment]
> put a giant "Join the Discord" thingy on that page btw

— @dcramer

**Comment by chadwhitacre** [comment]
"[How to Process Issues & PRs](https://www.notion.so/sentry/How-to-Process-Issues-PRs-e9657c0fa77d407ebe7c878076f63e35)"

**Comment by chadwhitacre** [comment]
CTA for recruiting

**Comment by chadwhitacre** [comment]
@jean85 at https://github.com/getsentry/open.sentry.io/issues/1#issuecomment-776645034 re: external core contributors:

> what to do in those cases where the client would need to be escalated to support (who I need to ping? how?); as of now I just pinged @HazAT on Discord, but that was it; it's not a reliable escalation mechanism

**Comment by chadwhitacre** [comment]
OpenGraph tags so we get nice links on social

h/t @jean85 on [Twitter](https://twitter.com/AlessandroLai/status/1369004190207533058)

**Comment by chadwhitacre** [comment]
We've started in on this. Brainstorm complete!
